### PR TITLE
1.1.0 rc

### LINKED ISSUE #45: Loading component is missing
**Describe the bug**
There should be an adequate component, prompted during the lazy-load. Currently the PWA has some lazy imports (`lazy = () => {}`) that are unfortunately handled with just one line instead of a properly styled component

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the website using Google Chrome
2. Enable throttling in the `Networks` tab for `Slow 3G`
3. Reload the website
4. See simple message on the Death Star plans

**Expected behaviour**
A well structured and designed loading component should be prompted 

**Additional context**
No 3rd party library should be used to prompt the loading component

### PR DESCRIPTION
**Pull request by winniepukki**
Fixes #45 #15 #52 
Release version 1.1.0 candidate branch

### CODE REVIEW

File: src/app/component/Loading/Loading.component.js [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+                      stroke="var(--tea-color)"
+                      strokeWidth="2"
+                    />
+                    <path
+                      className="teabag"
+                      fill="var(--tea-color)"
+                      fillRule="evenodd"
+                      clipRule="evenodd"
+                      d="M16 25V17H14V25H12C10.3431 25 9 26.3431 9 28V34C9 35.6569 10.3431 37 12 37H18C19.6569 37 21 35.6569 21 34V28C21 26.3431 19.6569 25 18 25H16ZM11 28C11 27.4477 11.4477 27 12 27H18C18.5523 27 19 27.4477 19 28V34C19 34.5523 18.5523 35 18 35H12C11.4477 35 11 34.5523 11 34V28Z"
+                    />
```
Comment (elinapeshelee) [inline src/app/component/Loading/Loading.component.js:61]: I am sure there are ways to avoid such `svg` file usage. Did you investigate?

File: src/app/query/ProductList.query.js [hunk 2]
```diff
@@ -1,3 +1,4 @@
+/* eslint-disable no-return-await */
```
Comment (elinapeshelee) [inline src/app/query/ProductList.query.js:1]: Please ensure there are no `eslint-disable` rules. Perhaps, this bug can be reported to the `Winniepukki-guardian` package

**Review by elinapeshelee — CHANGES_REQUESTED** [review]
Please mind the comments

File: src/app/component/Loading/Loading.component.js (hunk 1 above)
Comment (winniepukki) [reply src/app/component/Loading/Loading.component.js:61]: Currently under the investigation

File: src/app/query/ProductList.query.js (hunk 2 above)
Comment (winniepukki) [reply src/app/query/ProductList.query.js:1]: Thanks for noting that. Will take into the consideration

File: src/public/index.html [hunk 3]
```diff
@@ -9,7 +9,8 @@
     <!-- Meta Tags -->
     <meta name="description" content="">
     <meta name="keywords" content="">
-    <meta name="author" content="Trinat SIA">
+    <meta name="author" content="Aleksandrs Bogackins <a.bogackins@gmail.com>">
+    <meta name="theme-color" content="#cfa670">
```
Comment (winniepukki) [inline src/public/index.html:13]: Description and keywords are planned after receiving the `lv` locale from the business owners

**Review by winniepukki — COMMENTED** [review]
Please be aware of those notes

**Comment by winniepukki** [comment]
Running the smoke tests

**Review by elinapeshelee — APPROVED** [review]
Smoke passed. Please ensure you have adjusted the AWS Amplify runner on its' end
